---
name: Handle Release PRs

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.RELEASES_APP_ID }}
          private-key: ${{ secrets.RELEASES_APP_PRIVATE_KEY }}

      - name: Handle Release Creation
        uses: camunda/infra-global-github-actions/teams/infra/pull-request/release@26f13733a3084a650a2e5a32500c1c2b322995e3
        with:
          github-token: ${{ steps.app-token.outputs.token }}
